entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

providers:
  docker:
    network: global
    exposedByDefault: false

api:
  dashboard: true
  insecure: false

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /certs/acme.json
      email: <YOUR_EMAIL>
      httpChallenge:
        entryPoint: web

ping: { }
log: { }
accessLog: { }